### ISSUE TITLE
Can't delete project

### ISSUE THREAD

**Issue by DargieDChouwy** [ForestAdmin/lumber#174] opened 2018-10-11 12:28 UTC
Hello,

I can't delete project. When I click on the trashcan nothing happens. I can select a project and do what I want to do.

I have got an error in F12 console : 

> TypeError: "this.get(...) is null"

![capture d ecran du 2018-10-11 14-27-18](https://user-images.githubusercontent.com/35135877/46803989-cecf1600-cd61-11e8-9f1b-9f408d9bc510.png)

**Comment by arnaudbesnier** [comment] 2019-08-29 09:55
Hi @DargieDChouwy let me close this issue as we cannot reproduce it.
Feel free to reopen it if necessary. 🙏

**Closed by arnaudbesnier** 2019-08-29 09:55 UTC
Labels: bug, forest admin related
