### ISSUE TITLE
401 when trying to log in to lumber admin

### ISSUE THREAD

**Issue by jugaltheshah** [ForestAdmin/lumber#105] opened 2017-08-22 00:49 UTC
Hi all,

I'm able to create a project fine using lumber-generate. It seems to create what it needs in a folder with the project name I specify. Furthermore, I'm able to go to the url it directs me to, http://app.forestadmin.com. The problem is, once I log in to forest admin using my username and password, it asks me to choose which project, and asks for my password again. At this stage, it flashes a toast notification on the top right of the site. "Login Your password is incorrect, please try again."

Once this happens, in the console where I started the back-end, I see this:
OPTIONS /forest/sessions 200 0.435 ms - 2
POST /forest/sessions 401 1.567 ms - 383
Error
    at /Users/user/Projects/at/at-lumber-test/node_modules/express-jwt/lib/index.js:101:22
    at /Users/user/Projects/at/at-lumber-test/node_modules/jsonwebtoken/index.js:54:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I have checked and re-checked that my password is correct. I made sure it wasn't asking for the DB password. I've reset my password multiple times using the password reset feature. I even tried creating an account using another email address. Nothing seems to want to work!

To confirm, it's asking for my forest user password, correct? The one I set when I first ran lumber-generate on a clean install?

**Comment by SeyZ** [comment] 2018-05-31 14:20
I can't reproduce this issue on my side. I think it's related to a old version of express-jwt and it should be fixed now. This issue is from a long time ago, so don't hesitate if you still have the problem

**Closed by SeyZ** 2018-05-31 14:20 UTC

**Comment by ps06756** [comment] 2018-09-05 17:02
I am still facing this issue.
