### ISSUE TITLE
Cannot find module '/var/www/html/lumber/bin/www' error

### ISSUE THREAD

**Issue by Ashh007** [ForestAdmin/lumber#11] opened 2016-11-15 05:51 UTC
Hi,
I had follows yr mention steps in system, but can not found any file or data while it got successful in-stallion. Nothing in found in directory & postgres.
Can u tell  me what is issue in this?

**Comment by ryanjrose** [comment] 2016-11-16 00:20
Im having the same issue trying to install on OSX

```
$ cd "ButtLiver" && node ./bin/www
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/johnsmith/Projects/lumber/ButtLiver/bin/www'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by SeyZ** [comment] 2016-11-16 03:54
@Ashh007 and @ryanjrose can you just do a `ls` on the generated directory (`Test_Lumber` for @ryanjrose ) and show here the output?

**Comment by cyanglee** [comment] 2016-11-18 07:51
Hi @Ashh007, I am having the same issue and here is the result from ```ls```

```
total 0
drwxr-xr-x  4 cyanglee  staff   136B Nov 15 11:15 .
drwxr-xr-x  6 cyanglee  staff   204B Nov 15 11:15 ..
drwxr-xr-x  2 cyanglee  staff    68B Nov 15 11:15 etc
drwxr-xr-x  2 cyanglee  staff    68B Nov 15 11:15 node_modules
```

**Comment by Ashh007** [comment] 2016-11-28 05:10
Hi @SeyZ  getting same in my directory

**Comment by SeyZ** [comment] 2016-11-28 07:25
Hey @Ashh007 Can you verify you have data in your database (not just the schema) ?

**Comment by clh021** [comment] 2016-12-14 16:17
Hi @SeyZ getting same in my directory, And there no change in my database.

```bash
root@20de8211ee05:/data# lumber generate
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  mysql
? What's the database name? lumber
? What's the database hostname? mysql
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]  ****
? Choose a project name:  Gift

cd Gift && npm install...
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v7.2.0
npm info lifecycle undefined~preinstall: undefined
npm info linkStuff !invalid#1
npm info lifecycle undefined~install: undefined
npm info lifecycle undefined~postinstall: undefined
npm info lifecycle undefined~prepublish: undefined
npm WARN enoent ENOENT: no such file or directory, open '/data/Gift/package.json'
npm WARN Gift No description
npm WARN Gift No repository field.
npm WARN Gift No README data
npm WARN Gift No license field.
npm info ok 

👍  Hooray, installation success! 👍

Run your admin microservice:
$ cd "Gift" && node ./bin/www

root@20de8211ee05:/data# ls -la Gift/
total 16
drwxr-xr-x 4 root root 4096 Dec 14 16:12 .
drwxrwxr-x 3 node node 4096 Dec 14 16:12 ..
drwxr-xr-x 2 root root 4096 Dec 14 16:12 etc
drwxr-xr-x 2 root root 4096 Dec 14 16:12 node_modules
root@20de8211ee05:/data# cd "Gift" && node ./bin/www
module.js:472
    throw err;
    ^

Error: Cannot find module '/data/Gift/bin/www'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
root@20de8211ee05:/data/Gift# 
```

**Comment by sayeko** [comment] 2017-02-01 07:03
same issue

**Comment by arnaudbesnier** [comment] 2019-09-10 14:59
Hi there,
As the issue is pretty old, and lumber changed a lot, I think we can close this issue.
I am pretty confident that this is fixed with the latest Lumber versions.

🌲🌲🌲

**Closed by arnaudbesnier** 2019-09-10 14:59 UTC
Labels: bug
