### ISSUE TITLE
Error Generating 

### ISSUE THREAD

**Issue by sm-tradeboox** [ForestAdmin/lumber#251] opened 2019-08-27 10:07 UTC
Testing Lumber for the first time, am quite disappointed that I can't even do the simple project generating step.

```
$ lumber generate -c postgres://testusr0:testpw0@localhost:5432/testdb0 Lumbr
? Does your database require a SSL connection?  No
? What's the IP/hostname on which your application will be running?  localhost
? What's the port on which your application will be running?  3000
> Your database is empty.
> Please, create some tables before running generate command.
```

Obviously my database is not empty!

```
/Applications/Postgres.app/Contents/Versions/11/bin/psql -p5432 "testdb0"
rhodium:~ sm$ /Applications/Postgres.app/Contents/Versions/11/bin/psql -p5432 "testdb0"
psql (11.3)
Type "help" for help.

testdb0=# \d
           List of relations
 Schema |    Name    | Type  |  Owner  
--------+------------+-------+---------
 public | actionlist | table | smishra
 public | entitynet  | table | smishra
(2 rows)
```
Using --
```
$ lumber -V
2.3.5
```

**Comment by arnaudbesnier** [comment] 2019-08-27 10:14
Hi @sm-tradeboox, thanks for the feedback.
Maybe it is an error message issue.

Does your `testusr0` have access to one of those 2 tables?

**Comment by sm-tradeboox** [comment] 2019-08-28 05:28
Hi. Yes, user is owner of both tables. Both tables were created by the same user as the login credentials.

**Comment by rap2hpoutre** [comment] 2019-10-18 14:50
Hi @sm-tradeboox! Sorry for late answer 😓 

It seems `lumber generate` did not asked you for a schema, which is not the normal behavior! It may be a resolved issue, since I can not reproduce the problem anymore (I am prompted for a schema in all my tests). Could you try again after upgrading your lumber install (e.g `npm i -g lumber-cli@latest`) with this command (I added a `--schema public` to avoid prompt)

```
lumber generate -c postgres://testusr0:testpw0@localhost:5432/testdb0 --schema public Lumbr
```

**Comment by rap2hpoutre** [comment] 2020-08-17 15:12
Let me close this issue, feel free to reopen if you still facing this issue.

**Closed by rap2hpoutre** 2020-08-17 15:12 UTC
Labels: bug
