### ISSUE TITLE
Yarn package manager - lumber-generate(1) does not exist, try --help

### ISSUE THREAD

**Issue by raibima** [ForestAdmin/lumber#20] opened 2016-11-16 04:51 UTC
Installed lumber-cli via *yarn* (0.16.1), and couldn't get it running.

On Ubuntu 14.04, Node 6.

```
$ lumber generate

  lumber-generate(1) does not exist, try --help
```

```
$ lumber --help

  Usage: lumber [options] [command]


  Commands:

    generate    generate your admin microservice
    action      create a new action
    user        show your current logged user
    login       sign in to your account
    logout      sign out of your account
    help [cmd]  display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

**Comment by SeyZ** [comment] 2016-11-16 05:45
Hey @coderay1100 - I didn't know about yarn before. Can you tell me how you install `lumber-cli` with yarn?

**Comment by coderay1100** [comment] 2016-11-16 05:46
```yarn global add lumber-cli``` @SeyZ

**Comment by SeyZ** [comment] 2016-11-16 05:51
Hey @coderay1100 - I fixed an issue related to Windows ( #18 ) on the version 0.1.7.
Can you try with `lumber-cli@0.1.6` instead of the latest one? I just want to be sure it's not a regression :)

**Comment by coderay1100** [comment] 2016-11-16 06:04
@SeyZ you mean lumber-cli@**1.0.6**? It still couldn't seem to find the lumber-generate module. Running `lumber --version` gives me `1.0.1` though.

**Comment by SeyZ** [comment] 2016-11-16 06:10
@coderay1100 

- You're right, I meant 1.0.6 :)
- I push the version `1.0.8` to fix the `--version` option
- If you `git clone` this repo and you run `$ node lumber.js generate` --> is it working?

**Comment by coderay1100** [comment] 2016-11-16 06:20
I would assume it would work just fine cos this problem appears to occur only when the installation is done using yarn. I was able to run `lumber generate` using lumber-cli installed from npm.

**Comment by SeyZ** [comment] 2016-11-16 06:46
Ok got it. It's an issue about `yarn`. Thank you, I try to test it with yarn:
`yarn global add lumber-cli@latest`

Installation success but can't find where my binary is :/

**Comment by coderay1100** [comment] 2016-11-16 09:49
Did you manage to find where your binary is? `yarn global bin` should do the trick

**Comment by arnaudbesnier** [comment] 2019-12-04 08:13
Hi @raibima,
I am closing this issue as Lumber changed a lot (and probably Yarn too) since your last interactions.

Feel free to reopen the ticket if the issue still occurs.

🌲🌲🌲

**Closed by arnaudbesnier** 2019-12-04 08:13 UTC
