### ISSUE TITLE
Tables are corretly generated but without data

### ISSUE THREAD

**Issue by popperz0r** [ForestAdmin/lumber#13] opened 2016-11-15 15:59 UTC
The source localhost:3000 is not retrieving data.

Error: Ember Data Request GET http://localhost:3000/forest/email returned a 0

**Comment by jeroenbourgois** [comment] 2016-11-15 19:36
Here I pressed return when prompted for the db password (on localhost, I use no password) and aftwerwards I saw `(using password: YES)`. So there might be something wrong there. Is it possible to update the db config afterwards?

**Comment by SeyZ** [comment] 2016-11-16 01:22
@jeroenbourgois You can update the DB credentials in the generated file `.env` -> `DATABASE_URL`

**Comment by SeyZ** [comment] 2016-11-16 03:55
@jeroenbourgois I fixed the issue you mentioned in the version 1.0.6. ref #17

**Comment by SeyZ** [comment] 2016-11-16 03:55
@popperz0r Is it the same issue?

**Comment by jeroenbourgois** [comment] 2016-11-22 11:11
@SeyZ thanks!

**Comment by popperz0r** [comment] 2016-11-22 11:20
I havent tested yet @SeyZ 

As soon as i can i will report back.

**Comment by SeyZ** [comment] 2016-11-23 17:22
@popperz0r Great, let me know when you have the time to test and reopen the issue if the problem is still there for you :)

**Comment by baconck** [comment] 2016-11-25 23:23
I am having a similar issue - my tables names are populated, but when trying to get data - only 400 errors.

```
vendor-6ae1141….js:10 Error: Ember Data Request GET http://localhost:3000/forest/events returned a 400
Payload (application/json; charset=utf-8)
[object Object]
    at i.t (vendor-6ae1141….js:10)
    at i (vendor-6ae1141….js:25)
    at n.handleResponse (vendor-6ae1141….js:25)
    at n.handleResponse (client-d164b32….js:33)
    at n [as handleResponse] (vendor-6ae1141….js:11)
    at n.c.error (vendor-6ae1141….js:25)
    at u (vendor-6ae1141….js:3)
    at Object.fireWith [as rejectWith] (vendor-6ae1141….js:3)
    at r (vendor-6ae1141….js:4)
    at XMLHttpRequest.<anonymous> (vendor-6ae1141….js:5)
```

When trying to create a new record

```
event_ticket
getaddrinfo ENOTFOUND tix tix:3306
```

MySQL db
Lumber 1.1.1

**Comment by emresebat** [comment] 2017-01-27 11:34
Hi 

I'm also having this issue, my database is postgresql and it's hosted on AWS RDS. Since the tables can be generated, I don't think it's a connection issue. 

My error shows:
[forest] 🌳🌳🌳  getaddrinfo ENOTFOUND dbadmin dbadmin:5432

Why my database username is used like an address here? I have some special chars in my password can it be broking the database url?

I created a project before which is also postgresql on localhost and did not have this problem.

**Comment by emresebat** [comment] 2017-03-25 11:27
Hi

I fixed my own problem, the problem occurs if database password has ? or any other special chars in it.

**Comment by SeyZ** [comment] 2017-03-30 21:23
Hey guys, let me close this issue. I think this one is a little bit "generic". Feel free to create a new one for your specific problem (if you still have one 😄  )

Cheers!

**Closed by SeyZ** 2017-03-30 21:23 UTC
Labels: bug
